version: '2'
services:
    myapp1-app:
        image: myapp1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myapp1-mysql:3306/myapp1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myapp1-mysql:
        extends:
            file: mysql.yml
            service: myapp1-mysql
